name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14' # Specify your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build and Test
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # Use your GitHub Secret here
      run: |
        npm run build
        npm test
